Repository hamzaplojovic/centarnit, pull requests merged in 2022-09, with the labels that each got.

#2 CRUD for users
  backend/__pycache__/main.cpython-310.pyc
  backend/main.py
  backend/routers/__pycache__/users.cpython-310.pyc
  backend/routers/users.py
Labels: enhancement

#4 Merge to hamza branch
  backend/__pycache__/main.cpython-310.pyc
  backend/main.py
  backend/routers/__pycache__/users.cpython-310.pyc
  backend/routers/users.py
Labels: duplicate

#5 CRUD Repository functions for users
  backend/__pycache__/main.cpython-310.pyc
  backend/main.py
  backend/repo/__pycache__/users.cpython-310.pyc
  backend/repo/users.py
  backend/routers/__pycache__/users.cpython-310.pyc
  backend/routers/users.py
  backend/schemas/__pycache__/user.cpython-310.pyc
  backend/schemas/user.py
Labels: enhancement

#10 quick navbar fix
  app/src/components/HomeCards/HomeCards.tsx
  app/src/components/HomeCards/HomeCardsStyles.tsx
  app/src/components/Navbar/Navbar.tsx
  app/src/components/Navbar/NavbarComponents/NavbarData.tsx
Labels: bug, enhancement

#12 login and signup for tomorrow
  app/src/components/Login/Login.tsx
  app/src/components/SignUp/SignUp.tsx
Labels: documentation, help wanted

#15 Moving license and template stuff to my branch too
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  LICENSE
  README.md
Labels: wontfix

#18 Login and dashboard page
  api/.deta/prog_info
  api/.deta/state
  api/__pycache__/main.cpython-310.pyc
  api/main.py
  api/repo/__pycache__/login.cpython-310.pyc
  api/repo/__pycache__/news.cpython-310.pyc
  api/repo/__pycache__/users.cpython-310.pyc
  api/repo/login.py
  api/repo/news.py
  api/repo/users.py
  api/requirements.txt
  api/routers/__pycache__/login.cpython-310.pyc
  api/routers/__pycache__/token.cpython-310.pyc
  api/routers/__pycache__/users.cpython-310.pyc
  api/routers/login.py
  api/routers/token.py
  api/routers/users.py
  api/schemas/__pycache__/user.cpython-310.pyc
  api/schemas/token.py
  api/schemas/user.py
  app/README.md
  app/src/components/App.tsx
  app/src/components/Dashboard/Dashboard.tsx
  app/src/components/HomeCards/CardItem.tsx
  app/src/components/HomeCards/HomeCards.tsx
  app/src/components/HomeCards/HomeCardsStyles.tsx
  app/src/components/Login/Login.tsx
  app/src/components/Login/LoginStyles.tsx
  app/src/components/Me/Me.tsx
  app/src/components/Navbar/Navbar.tsx
  app/src/components/Navbar/NavbarComponents/NavbarData.tsx
  app/src/components/Navbar/NavbarComponents/NavbarStyles.tsx
  app/src/components/News/News.tsx
  app/src/components/Projects/Projects.tsx
  app/src/components/Switch/Switch.tsx
  app/src/components/Switch/SwitchStyles.tsx
  app/src/components/Users/Users.tsx
  app/src/components/routes.tsx
  app/src/hooks/useData.tsx
  app/src/index.tsx
Labels: enhancement

#19 Mergin Code of Conduct and Readme to the branch
  CODE_OF_CONDUCT.md
  README.md
Labels: wontfix
